# Generated by Django 4.1.4 on 2023-06-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='startbid',
            new_name='price',
        ),
    ]
