# Generated by Django 4.1.4 on 2023-06-28 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_categories_listings_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.categories'),
            preserve_default=False,
        ),
    ]
